-- Per-request event lookup: "show me everything that happened during
-- request X, oldest first". Generated by populate_agent_events.py: each
-- request gets a batch of agent_events (tool-call hook events) and
-- system_events (kernel/process-level events) sharing its request_id.


-- 1. All agent_events (tool-call hook events) for a request, oldest first.
SELECT *
FROM agent_events
WHERE request_id = :request_id
ORDER BY ts;


-- 2. All system_events (kernel/process-level events) for a request, oldest first.
SELECT *
FROM system_events
WHERE request_id = :request_id
ORDER BY ts;
